name: Weathering
version: 0.1
description: weather the Cobblestone and the Stonebricks
author: Bootscreen
website: http://bootscreen.eu

main:  me.bootscreen.weathering.Weathering

commands:
  weathering:
    aliases: wtg
    description: Weathering commands
    usage: |
           Usage:
           /<command> - shows the Version and the Usage
           /<command> <radius> - starts the weathering in the given radius