name: Weathering
version: 0.3
description: weather the Cobblestone and the Stonebricks
author: Bootscreen
website: http://bootscreen.eu
dev-url: http://dev.bukkit.org/server-mods/weathering/

main:  me.bootscreen.weathering.Weathering

commands:
  weathering:
    aliases: wtg
    description: Weathering commands
    usage: |
           Usage:
           /<command> - shows the Version and the Usage
           /<command> <radius> - starts the weathering in the given radius


permissions:
    weathering:
        description: Allows the Player to use the weathering command.
        default: op